runner_type: Train 
random_seed: 42
num_epochs: 3
learning_rate: 0.01

save_dir: ./save/
pre_trained: False
pre_model_path: ./save/models/best_model.pt

data_config:
    dataclass: MuonDataset.MuonEnergyDataset 
    batch_size: 1024
    signal_scale_factor: 800
    path_save_graphs: ./save/
    train: [
        "/lustre/collider/mocen/project/hailing/machineLearning/workspace_after_20240529/mltoolkit/preprocess/train/*_1.pt",
    ]
    validation: [
        "/lustre/collider/mocen/project/hailing/machineLearning/workspace_after_20240529/mltoolkit/preprocess/validation/*1.pt",
    ]
    test: [
        "/lustre/collider/mocen/project/hailing/machineLearning/workspace_after_20240529/mltoolkit/preprocess/test/*1.pt",
    ]

metric_config:
    metric: RegressionMetric.RegressionMetric
    loss_function: SmoothL1Loss

network_config:
    Network: Transformer
    model_setting:
        block_params: [
                # out_channels, heads, dim_linear_block, dropout
                [16, 4, 64, 0.2],
                [32, 4, 128, 0.2],
                [32, 4, 128, 0.2],
                [16, 4, 64, 0.2],
        ]
        fc_params: [
            [0.1, 8],
            [0.1, 4],
        ]
        dim_embedding: 32
        input_features: 5
        output_classes: 1
