runner_type: Train 
random_seed: 42
num_epochs: 25

save_dir: ./save/
pre_trained: False
pre_model_path: ./save/best_model.pt

data_config:
    data_class: HadHadDataset.HadHadGGFHighDataset 
    fold_id: 0
    total_folds: 3
    batch_size: 1024
    signal_scale_factor: 800
    path_save_graphs: ./save/
    ntuple_path_list: [
        /lustre/collider/mocen/project/bbtautau/hhard/lxplus-sync/sample_hadhad/hhttbb.root,
        /lustre/collider/mocen/project/bbtautau/hhard/lxplus-sync/sample_hadhad/ttbar.root,
    ]

metric_config:
    metric: ClassificationMetric.ClassificationMetric
    loss_function: CrossEntropyLoss

network_config:
    Network: AttentionNet
    model_setting:
        block_params: [
                # out_channels, heads, dim_linear_block, dropout
                [16, 4, 64, 0.2],
                [32, 4, 128, 0.2],
                [32, 4, 128, 0.2],
                [16, 4, 64, 0.2],
        ]
        fc_params: [
            [0.1, 8],
            [0.1, 4],
        ]
        dim_embedding: 32
        global_features: 6
        edge_features: 3
        input_features: 8
        output_classes: 2
